### ISSUE TITLE
Question: Radar references

### ISSUE THREAD

**Issue by ib00** [cg-saarland/hussar#2]
Can you recommend some basic introduction (books, papers, tutorials) to automotive radar?

**Comment by iRath96** [comment]
Not for automotive radar, unfortunately. This project was mostly concerned with the wave propagation effects of radar and how these can be efficiently simulated using Monte Carlo techniques from computer graphics. Regarding sensors, we are also more on the low-level side of things (basic signal chain, ADC, Fourier transforms, etc) instead of high-level aspects like detecting and classifying objects.

I can recommend looking into FMCW radars, as they are popular for automotive radar. In particular, Texas Instruments has some nice white papers outlining how these operate on the lower levels. If you are interested in wave propagation, then looking into things like physical optics can be helpful. I found the EMAG Technologies Wiki to give a nice overview over physical optics and other computational electromagnetics techniques.
